/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rojberr.tic-tac-toe;

import org.junit.Test;
import static org.junit.Assert.*;

public class tictactoeTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
